# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  image: quay.io/buildah/stable
  stage: build
  variables:
    IMAGE_TAG: $CI_REGISTRY:5001/iam/uh-grouper/grouper:4.1.6-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA
    DEPLOY_TAG: $CI_REGISTRY:5001/iam/uh-grouper/grouper:4.1.6-8
  script:
    - buildah login --tls-verify=false -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY:5001
    - echo $CI_COMMIT_TIMESTAMP
    - buildah bud --build-arg-file=build.args -t $IMAGE_TAG .
    - buildah tag $IMAGE_TAG $CI_REGISTRY:5001/iam/uh-grouper/grouper:4.1.6-$CI_COMMIT_BRANCH-latest
    - buildah tag $IMAGE_TAG $DEPLOY_TAG
    - buildah push --tls-verify=false $IMAGE_TAG
    - buildah push --tls-verify=false $IMAGE_TAG $CI_REGISTRY:5001/iam/uh-grouper/grouper:4.1.6-$CI_COMMIT_BRANCH-latest
    - buildah push --tls-verify=false $DEPLOY_TAG
