# .gitlab-ci.yml is a root Grouper CI/CD pileline template.

stages:          # Stage the jobs.
  - build

build-job:       # Build job.
  image: quay.io/buildah/stable
  stage: build
  variables:
    IMAGE_TAG: $CI_REGISTRY:5001/iam/uh-grouper/grouper:4.1.6-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA
    DEPLOY_TAG: $CI_REGISTRY:5001/iam/uh-grouper/grouper:4.1.6-12
  script:
    - buildah login --tls-verify=false -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY:5001
    - echo $CI_COMMIT_TIMESTAMP
    - buildah bud --build-arg-file=build.args -t $IMAGE_TAG .
    - buildah tag $IMAGE_TAG $CI_REGISTRY:5001/iam/uh-grouper/grouper:4.1.6-$CI_COMMIT_BRANCH-latest
    - buildah tag $IMAGE_TAG $DEPLOY_TAG
    - buildah push --tls-verify=false $IMAGE_TAG
    - buildah push --tls-verify=false $IMAGE_TAG $CI_REGISTRY:5001/iam/uh-grouper/grouper:4.1.6-$CI_COMMIT_BRANCH-latest
    - buildah push --tls-verify=false $DEPLOY_TAG
