ARG GROUPER_VERSION
ARG DEPLOYMENT_CN

FROM i2incommon/grouper:${GROUPER_VERSION} as install

COPY /src/main/docker/slashRoot/ /

ENV CONTAINER_HOST_DOMAIN=${DEPLOYMENT_CN}

RUN chown tomcat /opt/tomcat/bin/self-signed-cert.sh
RUN /opt/tomcat/bin/self-signed-cert.sh

ENV GROUPER_UI_GROUPER_AUTH="true"
