ARG GROUPER_VERSION

FROM i2incommon/grouper:${GROUPER_VERSION} as install

COPY /src/main/docker/slashRoot/ /

RUN chmod +x /opt/keypairs/self-signed-cert.sh

ENV GROUPER_RUN_TOMCAT_NOT_SUPERVISOR="true"
ENV RUN_SHIB_SP="false"

CMD ws
