ARG GROUPER_VERSION

FROM i2incommon/grouper:${GROUPER_VERSION} as install

COPY /src/main/docker/slashRoot/ /

RUN chown tomcat /opt/tomcat/bin/self-signed-cert.sh

ENV GROUPER_RUN_TOMCAT_NOT_SUPERVISOR="true"
ENV GROUPER_UI_GROUPER_AUTH="true"
ENV RUN_SHIB_SP="false"

CMD daemon
