ARG GROUPER_VERSION

FROM i2incommon/grouper:${GROUPER_VERSION} as install

FROM amazoncorretto:8u252

ARG GROUPER_VERSION

COPY --from=install /opt/grouper/grouperWebapp /opt/grouper/grouperWebapp

RUN cp /opt/grouper/grouperWebapp/WEB-INF/libUiAndDaemon/* /opt/grouper/grouperWebapp/WEB-INF/lib

COPY /src/main/docker/slashRoot/ /

ENV GROUPER_VERSION ${GROUPER_VERSION}

ENTRYPOINT ["/opt/grouper/grouperWebapp/WEB-INF/bin/gsh.sh", "-loader"]