FROM i2incommon/grouper:2.5.22 as install
FROM scalding/grouper-custom:2.5.22

COPY --from=install /opt/tomee /opt/tomee

RUN cp /opt/grouper/grouperWebapp/WEB-INF/libUiAndDaemon/* /opt/grouper/grouperWebapp/WEB-INF/lib \
 && rm /opt/tomee/bin/setenv.sh