# The stack.yml file defines the services that Portainer will deploy and
# manage. The images must already be in the repository.
# - See .gitlab-ci.yml for the pipeline build configuration.
#
# Image deployment by Portainer is triggered by changing .gitlab-ci.yml. Be
# sure to bump up the image file index deploy tag index by +1 here and in
# the stack.yml file.
services:
  ui:
    # Also update portainer/stack.yml if the grouper version changes.
    GROUPER_VERSION: 4.2.0
    # Bump up the index here and in .gitlab-ci.yml to trigger a new deployment.
    GROUPER_TAG_ID: 47
    # Also update build.gradle & portainer/stack.yml if the image name changes.
    image: &grouper_image rep90.pvt.hawaii.edu:5001/iam/uh-grouper/grouper:$GROUPER_VERSION-$GROUPER_TAG_ID
    command: ui
    ports:
      - "8443:8443"
    user: root
    environment: &grouper_environment
      GROUPER_DATABASE_URL: ${GROUPER_DATABASE_URL}
      GROUPER_DATABASE_USERNAME: ${GROUPER_DATABASE_USERNAME}
      GROUPER_DATABASE_PASSWORD: ${GROUPER_DATABASE_PASSWORD}
      GROUPER_MORPHSTRING_ENCRYPT_KEY: ${GROUPER_MORPHSTRING_ENCRYPT_KEY}
      GROUPER_RUN_TOMCAT_NOT_SUPERVISOR: true
      GROUPER_LOG_TO_HOST: true
      RUN_SHIB_SP: false
      GROUPER_UI_GROUPER_AUTH: false
      GROUPER_AUTO_DDL_UPTOVERSION: V4.*.*
      GROUPER_UI_CONFIGURATION_EDITOR_SOURCEIPADDRESSES: 0.0.0.0/32
      PAC4J_ENABLED: true
      PAC4J_GROUPERCONTEXTURL: https://grouper-dev.its.hawaii.edu/grouper
      GROUPER_TOMCAT_MAX_HEADER_COUNT: "-1"
    volumes:
      - tls-keypairs:/opt/keypairs:ro
      - /home/grouper/grouper/logs:/opt/grouper/logs
      - /home/grouper/grouper/logs:/opt/tomcat/logs
  ws:
    image: *grouper_image
    command: ws
    ports:
      - "9443:8443"
    user: root
    environment:
      <<: *grouper_environment
    volumes:
      - tls-keypairs:/opt/keypairs:ro
      - /home/grouper/grouper/logs:/opt/grouper/logs
      - /home/grouper/grouper/logs:/opt/tomcat/logs
  daemon:
    image: *grouper_image
    command: daemon
    user: root
    environment:
      <<: *grouper_environment
    volumes:
      - tls-keypairs:/opt/keypairs:ro
      - /home/grouper/grouper/logs:/opt/grouper/logs
      - /home/grouper/grouper/logs:/opt/tomcat/logs
  logrotate:
    image: alpine:latest
    user: &user root
    # Passed to Dockerfile-logrotate
    environment:
      USER: *user
      HOME: /home/grouper
      APP_LOGS: /opt/grouper/logs
    volumes:
      - /home/grouper/grouper/logs:/opt/grouper/logs
volumes:
  tls-keypairs:
