# portainer/stack.yml - Portainer container deployment instructions
#
# To deploy: see the 2 BUMP sections below for triggering new deployments.
#            For example, bump ...grouper:4.2.0-18 to ...19.
#
# Note: Docker Compose files (which Portainer utilizes for stacks) do not
# natively support variable interpolation or substitution within image names.
# YAML anchors don't work either.
services:
  ui:
    environment: &grouper_environment
      # Grouper settings.
      GROUPER_DATABASE_URL: ${GROUPER_DATABASE_URL}
      GROUPER_DATABASE_USERNAME: ${GROUPER_DATABASE_USERNAME}
      GROUPER_DATABASE_PASSWORD: ${GROUPER_DATABASE_PASSWORD}
      GROUPER_MORPHSTRING_ENCRYPT_KEY: ${GROUPER_MORPHSTRING_ENCRYPT_KEY}
      GROUPER_RUN_TOMCAT_NOT_SUPERVISOR: true
      GROUPER_LOG_TO_HOST: true
      GROUPER_RUN_SHIB_SP: false
      GROUPER_UI_GROUPER_AUTH: false
      GROUPER_AUTO_DDL_UPTOVERSION: V4.*.*
      GROUPER_UI_CONFIGURATION_EDITOR_SOURCEIPADDRESSES: 0.0.0.0/32
      GROUPER_TOMCAT_MAX_HEADER_COUNT: "-1"
      PAC4J_ENABLED: true
      PAC4J_GROUPERCONTEXTURL: ${PAC4J_GROUPERCONTEXTURL}
      CERT_SUBJECT_TEST: ${CONTAINER_CERT_SUBJECT}
    ## BUMP 1 - bump the index here and in gitlab-ci.yml
    #           Update .gilab-ci.yml for Grouper version changes.
    image: &grouper_image rep90.pvt.hawaii.edu:5001/iam/uh-grouper/grouper:4.2.0-162
    command: sh -c '/opt/tomcat/bin/self-signed-cert.sh && ui'
    ports:
      - "8443:8443"
    user: &grouper_user root
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
    volumes: &grouper_volumes
      - /home/grouper/grouper/logs:/opt/grouper/logs
      - /home/grouper/grouper/logs:/opt/tomcat/logs
  ws:
    environment:
      <<: *grouper_environment
    image: *grouper_image
    command: ws
    ports:
      - "9443:8443"
    user: *grouper_user
    volumes:
      *grouper_volumes
  daemon:
    environment:
      <<: *grouper_environment
    image: *grouper_image
    command: daemon
    user: *grouper_user
    volumes:
      *grouper_volumes
  logrotate:
    environment:
      CONTAINER_HOST_DOMAIN: ${CONTAINER_HOST_DOMAIN}
    ## BUMP 2 - bump the index
    image: rep90.pvt.hawaii.edu:5001/iam/uh-grouper/logrotate-grouper:1.0.0-162
    user: *grouper_user
    command: ["crond", "-n"]
    volumes:
      - /home/grouper/grouper/logs:/opt/grouper/logs
