# portainer/stack.yml - Portainer container deployment instructions
#
# To deploy: see the 2 DEPLOY sections below for triggering new deployments.
#
# Docker Compose files (which Portainer utilizes for stacks) do not natively
# support variable interpolation or substitution within image names. YAML
# anchors don't work either.
services:
  ui:
    environment: &grouper_environment
      # Grouper settings.
      GROUPER_DATABASE_URL: ${GROUPER_DATABASE_URL}
      GROUPER_DATABASE_USERNAME: ${GROUPER_DATABASE_USERNAME}
      GROUPER_DATABASE_PASSWORD: ${GROUPER_DATABASE_PASSWORD}
      GROUPER_MORPHSTRING_ENCRYPT_KEY: ${GROUPER_MORPHSTRING_ENCRYPT_KEY}
      GROUPER_RUN_TOMCAT_NOT_SUPERVISOR: true
      GROUPER_LOG_TO_HOST: true
      RUN_SHIB_SP: false
      GROUPER_UI_GROUPER_AUTH: false
      GROUPER_AUTO_DDL_UPTOVERSION: V4.*.*
      GROUPER_UI_CONFIGURATION_EDITOR_SOURCEIPADDRESSES: 0.0.0.0/32
      PAC4J_ENABLED: true
      PAC4J_GROUPERCONTEXTURL: https://grouper-dev.its.hawaii.edu/grouper
      GROUPER_TOMCAT_MAX_HEADER_COUNT: "-1"
    ## DEPLOY (1) - bump the index here and in gitlab-ci.yml
    # Also update build.args if the Grouper version changes.
    image: &grouper_image rep90.pvt.hawaii.edu:5001/iam/uh-grouper/grouper:4.2.0-99
    command: ui
    ports:
      - "8443:8443"
    user: &grouper_user root
    volumes: &grouper_volumes
      - tls-keypairs:/opt/keypairs:ro
      - /home/grouper/grouper/logs:/opt/grouper/logs
      - /home/grouper/grouper/logs:/opt/tomcat/logs
  ws:
    environment:
      <<: *grouper_environment
    image: *grouper_image
    command: ws
    ports:
      - "9443:8443"
    user: *grouper_user
    volumes:
      <<: *grouper_volumes
#      - tls-keypairs:/opt/keypairs:ro
#      - /home/grouper/grouper/logs:/opt/grouper/logs
#      - /home/grouper/grouper/logs:/opt/tomcat/logs
  daemon:
    environment:
      <<: *grouper_environment
    image: *grouper_image
    command: daemon
    user: *grouper_user
    volumes:
      <<: *grouper_volumes
  #      - tls-keypairs:/opt/keypairs:ro
  #      - /home/grouper/grouper/logs:/opt/grouper/logs
  #      - /home/grouper/grouper/logs:/opt/tomcat/logs
  logrotate:
    ## DEPLOY (2) - bump the index
    image: rep90.pvt.hawaii.edu:5001/iam/uh-grouper/logrotate-grouper:1.0.0-99
    user: *grouper_user
    command: ["crond", "-n"]
    volumes:
      - /home/grouper/grouper/logs:/opt/grouper/logs
volumes:
  tls-keypairs:
