# portainer/stack.yml
#
##>-DEPLOY-<##
# See the DEPLOY sections below.
##>--------<##
#
# Docker Compose files (which Portainer utilizes for stacks) do not natively
# support variable interpolation or substitution within image names.
services:
  ui:
    environment: &grouper_environment
      # Grouper settings.
      GROUPER_DATABASE_URL: ${GROUPER_DATABASE_URL}
      GROUPER_DATABASE_USERNAME: ${GROUPER_DATABASE_USERNAME}
      GROUPER_DATABASE_PASSWORD: ${GROUPER_DATABASE_PASSWORD}
      GROUPER_MORPHSTRING_ENCRYPT_KEY: ${GROUPER_MORPHSTRING_ENCRYPT_KEY}
      GROUPER_RUN_TOMCAT_NOT_SUPERVISOR: true
      GROUPER_LOG_TO_HOST: true
      RUN_SHIB_SP: false
      GROUPER_UI_GROUPER_AUTH: false
      GROUPER_AUTO_DDL_UPTOVERSION: V4.*.*
      GROUPER_UI_CONFIGURATION_EDITOR_SOURCEIPADDRESSES: 0.0.0.0/32
      PAC4J_ENABLED: true
      PAC4J_GROUPERCONTEXTURL: https://grouper-dev.its.hawaii.edu/grouper
      GROUPER_TOMCAT_MAX_HEADER_COUNT: "-1"
    ##>-DEPLOY-<##
    # Bump the index here and in .gitlab-ci.yml.
    # Also update build.args if the Grouper version changes.
    image: &grouper_image rep90.pvt.hawaii.edu:5001/iam/uh-grouper/grouper:4.2.0-79
    ##>--------<##
    command: ui
    ports:
      - "8443:8443"
    user: root
    volumes:
      - tls-keypairs:/opt/keypairs:ro
      - /home/grouper/grouper/logs:/opt/grouper/logs
      - /home/grouper/grouper/logs:/opt/tomcat/logs
  ws:
    environment:
      <<: *grouper_environment
    image: *grouper_image
    command: ws
    ports:
      - "9443:8443"
    user: root
    volumes:
      - tls-keypairs:/opt/keypairs:ro
      - /home/grouper/grouper/logs:/opt/grouper/logs
      - /home/grouper/grouper/logs:/opt/tomcat/logs
  daemon:
    environment:
      <<: *grouper_environment
    image: *grouper_image
    command: daemon
    user: root
    volumes:
      - tls-keypairs:/opt/keypairs:ro
      - /home/grouper/grouper/logs:/opt/grouper/logs
      - /home/grouper/grouper/logs:/opt/tomcat/logs
  logrotate:
    environment:
      <<: *grouper_environment
    ##>-DEPLOY-<##
    # Bump the index here and in .gitlab-ci.yml.
    image: rep90.pvt.hawaii.edu:5001/iam/uh-grouper/logrotate-grouper:1.0.0-79
    ##>--------<##
    user: root
    command: crontab -u root /var/spool/cron/logrotate.cron
    volumes:
      - /home/grouper/grouper/logs:/opt/grouper/logs
volumes:
  tls-keypairs:
