# The stack.yml file defines the services that Portainer will deploy and
# manage. The images must already be in the repository.
# - See .gitlab-ci.yml for the pipeline build configuration.
#
# Image deployment by Portainer is triggered by changing .gitlab-ci.yml. Be
# sure to bump up the image file index deploy tag index by +1 here and in
# the stack.yml file.
#
# Also update portainer/stack.yml if the grouper version changes.
services:
  ui:
    environment: &grouper_environment
      # Bump the index here and in .gitlab-ci.yml.
      DEPLOY_ID: 73
      # Also update build.args if the Grouper version changes.
      GROUPER_VERSION: 4.2.0
      # Grouper settings.
      GROUPER_DATABASE_URL: ${GROUPER_DATABASE_URL}
      GROUPER_DATABASE_USERNAME: ${GROUPER_DATABASE_USERNAME}
      GROUPER_DATABASE_PASSWORD: ${GROUPER_DATABASE_PASSWORD}
      GROUPER_MORPHSTRING_ENCRYPT_KEY: ${GROUPER_MORPHSTRING_ENCRYPT_KEY}
      GROUPER_RUN_TOMCAT_NOT_SUPERVISOR: true
      GROUPER_LOG_TO_HOST: true
      RUN_SHIB_SP: false
      GROUPER_UI_GROUPER_AUTH: false
      GROUPER_AUTO_DDL_UPTOVERSION: V4.*.*
      GROUPER_UI_CONFIGURATION_EDITOR_SOURCEIPADDRESSES: 0.0.0.0/32
      PAC4J_ENABLED: true
      PAC4J_GROUPERCONTEXTURL: https://grouper-dev.its.hawaii.edu/grouper
      GROUPER_TOMCAT_MAX_HEADER_COUNT: "-1"
    image: &grouper_image rep90.pvt.hawaii.edu:5001/iam/uh-grouper/grouper:${GROUPER_VERSION}-${DEPLOY_ID}
    command: ui
    ports:
      - "8443:8443"
    user: root
    volumes:
      - tls-keypairs:/opt/keypairs:ro
      - /home/grouper/grouper/logs:/opt/grouper/logs
      - /home/grouper/grouper/logs:/opt/tomcat/logs
  ws:
    environment:
      <<: *grouper_environment
    image: *grouper_image
    command: ws
    ports:
      - "9443:8443"
    user: root
    volumes:
      - tls-keypairs:/opt/keypairs:ro
      - /home/grouper/grouper/logs:/opt/grouper/logs
      - /home/grouper/grouper/logs:/opt/tomcat/logs
  daemon:
    environment:
      <<: *grouper_environment
    image: *grouper_image
    command: daemon
    user: root
    volumes:
      - tls-keypairs:/opt/keypairs:ro
      - /home/grouper/grouper/logs:/opt/grouper/logs
      - /home/grouper/grouper/logs:/opt/tomcat/logs
  logrotate:
    environment:
      <<: *grouper_environment
    image: rep90.pvt.hawaii.edu:5001/iam/uh-grouper/logrotate-grouper:1.0.0-${DEPLOY_ID}
    user: root
    command: crontab -u root /var/spool/cron/logrotate.cron
    volumes:
      - /home/grouper/grouper/logs:/opt/grouper/logs
volumes:
  tls-keypairs:
