# portainer/stack.yml - Portainer container deployment instructions
#
# To deploy: see the BUMP section below for triggering new deployments.
#            For example, bump ...grouper:4.2.0-18 to ...19.
#
# Note: Docker Compose files (which Portainer utilizes for stacks) do not
# natively support variable interpolation or substitution within image names.
# YAML anchors don't work either.
services:
  ui:
    ## BUMP - bump the index here and in gitlab-ci.yml
    #         Update .gilab-ci.yml for Grouper version changes.
    image: &grouper_image rep90.pvt.hawaii.edu:5001/iam/uh-grouper/grouper:4.2.0-233
    environment: &grouper_environment
      # Grouper settings.
      GROUPER_DATABASE_URL: ${GROUPER_DATABASE_URL}
      GROUPER_DATABASE_USERNAME: ${GROUPER_DATABASE_USERNAME}
      GROUPER_DATABASE_PASSWORD: ${GROUPER_DATABASE_PASSWORD}
      GROUPER_MORPHSTRING_ENCRYPT_KEY: ${GROUPER_MORPHSTRING_ENCRYPT_KEY}
      GROUPER_RUN_TOMCAT_NOT_SUPERVISOR: true
      GROUPER_LOG_TO_HOST: true
      GROUPER_RUN_SHIB_SP: false
      GROUPER_UI_GROUPER_AUTH: false
      GROUPER_AUTO_DDL_UPTOVERSION: V4.*.*
      GROUPER_ENV: ${GROUPER_ENV}
      GROUPER_UI_URL: ${GROUPER_UI_URL}
      GROUPER_UI_CONFIGURATION_EDITOR_SOURCEIPADDRESSES: ${GROUPER_UI_CONFIGURATION_EDITOR_SOURCEIPADDRESSES}
      GROUPER_TOMCAT_MAX_HEADER_COUNT: "-1"
      PAC4J_ENABLED: true
      CONTAINER_CERT_SUBJECT: ${CONTAINER_CERT_SUBJECT}
    command: /bin/bash -c '/opt/tomcat/bin/self-signed-cert.sh && ui'
    ports:
      - "8443:8443"
    user: &grouper_user root
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
    volumes: &grouper_volumes
      - /home/grouper/grouper/logs:/opt/grouper/logs
      - /home/grouper/grouper/logs:/opt/tomcat/logs
  ws:
    image: *grouper_image
    environment:
      <<: *grouper_environment
    command: /bin/bash -c '/opt/tomcat/bin/self-signed-cert.sh && ws'
    ports:
      - "9443:8443"
    user: *grouper_user
    volumes:
      *grouper_volumes
  daemon:
    image: *grouper_image
    environment:
      <<: *grouper_environment
    command: /bin/bash -c '/opt/tomcat/bin/self-signed-cert.sh && daemon'
    user: *grouper_user
    volumes:
      *grouper_volumes
